#!/bin/bash
# ==============================================================================
# generate-mobile-ru.sh — генерит lists/mobile-ru.txt через RIPEstat API
#
# Используется GitHub Actions раз в неделю.
# Можно запускать локально: bash .github/scripts/generate-mobile-ru.sh > lists/mobile-ru.txt
#
# RIPEstat — публичный API без аутентификации. Никаких ключей не нужно.
# Endpoint: https://stat.ripe.net/data/announced-prefixes/data.json?resource=ASxxxx
#
# Вывод: stdout пишет финальный lists/mobile-ru.txt с заголовком и CIDR'ами.
# ==============================================================================

set -o pipefail
export LANG=C LC_ALL=C

# Список AS — российские мобильные операторы (CGNAT pool'ы).
# Проверены через RIPEstat: stat.ripe.net/data/as-overview/data.json?resource=ASxxxx
# Включены: явные mobile/Vimpelcom AS. Исключены: МГТС fixed-line (AS25513),
# Mod MVNO (AS39855), gov-only AS.
declare -A AS_NAMES=(
    [8359]="МТС PJSC"
    [28884]="МТС Siberia"
    [12958]="T2 Mobile (Tele2)"
    [15378]="T2 Mobile (бывший Yota)"
    [41330]="T2 Mobile Novosibirsk"
    [42437]="T2 Mobile Rostov"
    [48190]="T2 Mobile Ekaterinburg"
    [31133]="MegaFon"
    [31163]="MegaFon Kavkaz"
    [12714]="MegaFon-AS (бэкбон)"
    [3216]="Vimpelcom (Beeline)"
    [8402]="Corbina (Vimpelcom)"
    [16345]="Beeline-AS"
)

# Порядок обхода (детерминированный для одинакового вывода)
AS_LIST=(8359 28884 12958 15378 41330 42437 48190 31133 31163 12714 3216 8402 16345)

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Генерим header
NOW=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
cat <<HEADER
# shieldnode mobile-RU AS whitelist
# nft set: mobile_ru_whitelist_v4 (CGNAT-friendly relaxed limits)
#
# Auto-generated by .github/scripts/generate-mobile-ru.sh
# Source: RIPEstat (https://stat.ripe.net/) — public API, no auth
# Updated: $NOW
#
# AS list (13):
HEADER

for asn in "${AS_LIST[@]}"; do
    name="${AS_NAMES[$asn]}"
    echo "#   AS$asn — $name"
done
cat <<'HEADER2'
#
# Format: один CIDR на строку, # = комментарий.
# Path-watcher (inotify) триггерит обновление nft set за <1 сек при изменении.

HEADER2

# Скачиваем prefixes для каждой AS
TOTAL_RAW=0
for asn in "${AS_LIST[@]}"; do
    URL="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS${asn}"

    # Retry 3 раза с backoff
    for attempt in 1 2 3; do
        if curl -fsSL --max-time 30 -A "shieldnode-mobile-ru-generator/1.0" \
            "$URL" -o "$TMP/as_${asn}.json" 2>/dev/null; then
            break
        fi
        if [ "$attempt" = "3" ]; then
            echo "ERROR: failed to fetch AS$asn after 3 attempts" >&2
            exit 1
        fi
        sleep $((attempt * 2))
    done

    # Парсим JSON через python (есть в любом ubuntu-latest runner'е)
    python3 -c "
import sys, json
try:
    with open('$TMP/as_${asn}.json') as f:
        data = json.load(f)
    for p in data['data']['prefixes']:
        print(p['prefix'])
except Exception as e:
    print(f'ERROR parsing AS${asn}: {e}', file=sys.stderr)
    sys.exit(1)
" >> "$TMP/raw_prefixes.txt"

    # Rate-limit: RIPEstat не любит burst >5 req/sec
    sleep 0.3
done

TOTAL_RAW=$(wc -l < "$TMP/raw_prefixes.txt")
echo "# Raw prefixes from RIPEstat: $TOTAL_RAW (before IPv4-only filter + dedup)" 

# Фильтр: только IPv4, только валидные CIDR'ы, исключаем bogons
awk -F'[./]' '
BEGIN { OFS="." }
# Только IPv4-формат: 4 октета + /prefix
NF != 5 { next }
{
    o1 = $1 + 0; o2 = $2 + 0; o3 = $3 + 0; o4 = $4 + 0
    prefix = $5 + 0

    # Валидируем октеты
    if (o1 < 0 || o1 > 255 || o2 < 0 || o2 > 255 || o3 < 0 || o3 > 255 || o4 < 0 || o4 > 255) next
    if (prefix < 8 || prefix > 32) next

    # Bogons фильтр
    if (o1 == 0)   next   # 0.0.0.0/8
    if (o1 == 10)  next   # 10.0.0.0/8 RFC1918
    if (o1 == 127) next   # loopback
    if (o1 >= 224) next   # multicast / reserved
    if (o1 == 169 && o2 == 254) next   # link-local
    if (o1 == 172 && o2 >= 16 && o2 <= 31) next   # 172.16.0.0/12
    if (o1 == 192 && o2 == 168) next   # 192.168.0.0/16
    if (o1 == 100 && o2 >= 64 && o2 <= 127) next   # 100.64.0.0/10 CGNAT (ironic для mobile, но bogon)

    print $0
}' "$TMP/raw_prefixes.txt" | sort -u > "$TMP/clean.txt"

CLEAN_COUNT=$(wc -l < "$TMP/clean.txt")
echo "# IPv4 prefixes after filter + dedup: $CLEAN_COUNT"
echo ""

# Sanity check — должно быть >500 CIDR'ов для нормального RU mobile coverage
if [ "$CLEAN_COUNT" -lt 100 ]; then
    echo "ERROR: only $CLEAN_COUNT IPv4 CIDRs after filter (RIPEstat returned malformed data?)" >&2
    exit 1
fi

# Финальный вывод
cat "$TMP/clean.txt"
